---
- name: Update apt cache
  ansible.builtin.apt:
    update_cache: true
    update_cache_retries: 5
    update_cache_retry_max_delay: 12

- name: Update font cache
  ansible.builtin.command: fc-cache -f
  changed_when: true

- name: Reload systemd
  ansible.builtin.systemd:
    daemon_reload: true

- name: Restart Sunshine user service
  ansible.builtin.command: "loginctl kill-user {{ dev_user }}"
  changed_when: true
  failed_when: false
