Section "InputClass"
    Identifier "Synaptics touchpad catchall"
    MatchIsTouchpad "on"
    MatchDevicePath "/dev/input/event*"
    Driver "libinput"
    Option "Tapping" "on"
    Option "TappingDrag" "on"
    Option "TappingDragLock" "on"
    Option "NaturalScrolling" "on"
    Option "ClickMethod" "clickfinger"
    Option "DisableWhileTyping" "on"
    Option "ScrollMethod" "twofinger"
    Option "HorizontalScrolling" "on"
    Option "AccelProfile" "adaptive"
EndSection
